### ISSUE TITLE
Disenchanter gets other icon when Advanced Rocketry is installed

### ISSUE THREAD

**Issue by D3nnis3n** [Impelon/Disenchanter#22]
There seems to be something more wrong, your disenchanter get's the following Icon, when Advanced Rocketry is installed:

https://ibb.co/dm8a0b

It's an battery pack.

**Comment by Impelon** [comment]
To be honest, I do think this happens because of #12, because other Mods might disregard custom resource-locations. 
Maybe I'll remove that, I've done that so I can use lowercase file names in 1.10 and below...

**Comment by D3nnis3n** [comment]
Thanks for the Information.
For now, as of this issue and the one with Fancy Block Particles we will remove your mod and rely on Cyclics Unchanter, as this is confusing for most Players. Yes, we could add it to the blacklist of FBP, but after testing a really Long time for many blocks (and opening issues on FPB) every issue could be resolved by the author without the Need of fiddling in config files, so we prefer to not do that for a single block that has other issues.

But i would really like if you kept me updated if you fix that or not. For now, Advanced Rocketry unfortunatley is more important on the Server for dimensional travel and this does confuse our Players.

**Comment by Impelon** [comment]
I'll try to get around and fix this in the next update, but this will probably take a while, until I get the motivation to work on this again xD
