### ISSUE TITLE
Books obtained from disenchanting cannot be applied to tools through an anvil

### ISSUE THREAD

**Issue by pajicadvance** [Impelon/Disenchanter#23]
Version 1.5 for 1.12, Minecraft Forge 14.23.0.2491

As the title says. [Here is a small demonstration video](https://gfycat.com/gifs/detail/smallbackcats)

**Comment by Impelon** [comment]
Mhm.. yeaaaaa... give me a sec.

**Comment by Impelon** [comment]
So yeah, It's going to be fixed soon, probably tomorrow. I've actually fixed it already, but I'm too tired to upload the result now; I'm sorry, you're going have to be patient.

**Comment by pajicadvance** [comment]
No problem, take your time - I am merely here just to inform you of the bug :)

**Comment by Impelon** [comment]
Done here, hoxfix will be on curse in a few minutes.
