### ISSUE TITLE
Strange cross-compat issue with this mod and storage boats

### ISSUE THREAD

**Issue by Sunconure11** [Impelon/Disenchanter#25]
![screenshot 2017-11-29 07 21 49](https://user-images.githubusercontent.com/5614902/33374905-fe58dc88-d4d5-11e7-884f-966924ad05e3.png)

https://minecraft.curseforge.com/projects/storage-boats-mod

**Comment by Impelon** [comment]
What exactly is the problem here? I do see that the texture is kinda messed up, but I do not exactly understand how that relates to my mod?

**Comment by Impelon** [comment]
Ok, actually, I found your issue on the storage-boats issue-tracker...
https://minecraft.curseforge.com/projects/storage-boats-mod/issues/27

Yeah, probs #12 again ._. I guess it does cause a lot of problems with other mods ...

**Comment by Impelon** [comment]
(Hopefully) fixed!
