### ISSUE TITLE
No way to automatically insert item into book slot.

### ISSUE THREAD

**Issue by nitefang** [Impelon/Disenchanter#34]
There is currently now way to use a vanilla hopper to insert a book or any item into any slot other than the first slot which is intended for enchanted items. No matter what side of the table the hopper is placed it will attempt to put the item into the first slot.

**Comment by Impelon** [comment]
The way it works at the moment is, that you first have to insert the item you want to disenchant, afterwards you can insert to book through the same hopper, or alternatively another hopper. 
I could make it so that books always prioritize the book slot maybe...
