### ISSUE TITLE
Multiple books may be inserted into the table using a hopper, but it will appear that only a single book is inserted.

### ISSUE THREAD

**Issue by nitefang** [Impelon/Disenchanter#36]
If using a hopper to attempt to insert a book into the table, the hopper will continue to insert books into the first slot until it is full, then begin inserting books into the second slot until that slot is full as well. In the GUI both slots will appear to only have 1 book in them but a full stack may be removed.

**Comment by Impelon** [comment]
Yep somewhere here I messed up. The Stack Limit gets ignored by hoppers and similar. 
This issue is in 1.12, right?

**Comment by nitefang** [comment]
Sorry I totally forgot to add that info. Yea, it is 1.12.2, the latest version of your mod and Forge version 2655
