### ISSUE TITLE
[1.10.2] NoClassDefFoundError on server

### ISSUE THREAD

**Issue by tommyTT** [Impelon/Disenchanter#4]
When putting version 1.3 of the mod on a server it crashes with a NoClassDefFoundError.

Minecraft 1.10.2
Forge Version 12.18.1.2046
Disenchanter: disenchanter-[1.9.4]1.3.jar

http://pastebin.com/2mpEs48q

**Comment by Impelon** [comment]
Fixed as of the 1.4 update; Caused by me being lazy with the 1.9/1.10 BlockColors: I apologise ^^
