### ISSUE TITLE
[Request] Void Without Books, Thermal Expansion ItemDuct Support

### ISSUE THREAD

**Issue by Andronomos** [Impelon/Disenchanter#46]
I was wondering if you could add a table (or config option) that allows voiding enchantments from an item without requiring books and support ThermalExpansion's Itemducts?

I'm attempting to set up an automated system that takes weapons, tools and armor from my mob farm and sends them to a grinder to grind into base materials. The grinder does not accept damaged or enchanted items. So I have to repair and disenchant them first (no reliable way to filter enchanted from non enchanted items). Problem is none of the tables allow you to void enchantments without supplying books. I can't seem to get Itemducts to work with the disenchantment table so I can't input books or pull out the items either. I also don't need or want the enchanted books either as I'm using the Enchantments+ mod which allows me to enchant any item with almost any enchantment of my choosing.

**Comment by Impelon** [comment]
Sounds like a thing I could definitely work on next time I have time to...

**Comment by Impelon** [comment]
As a side note, I am guessing you're using the MFR Grinder, is that correct? If that's the case, MFR has a disenchanter, too. If not, nevermind I guess ^^

Itemducts not working is related to #44.

**Comment by Andronomos** [comment]
Last I checked, MFR hadn't updated to 1.12 unfortunately. I'm using the Grinder from [Cyclic ](https://minecraft.curseforge.com/projects/cyclic). It turns it it has a disenchantment anvil that suits my needs but I still think this would be a good feature to add to your mod when you get some time.
