### ISSUE TITLE
Critical: Dupe Bug using the Disenchanting Table

### ISSUE THREAD

**Issue by maxerium** [Impelon/Disenchanter#47]
After some testing from me and others, we've found out that you can basically get infinite enchanted books from a single item.

**How?**
You put the enchanted item into the disenchanter (with a book, just like normal).
You then proceed to press Q on the item - to drop it out of the disenchanter.

**What happens?**
You KEEP the book and can get it out of there, resulting in a duped enchantment.

**Further Information**
- Mod Version: **1.6**
- Forge Version: **14.23.5.2838**

**Comment by Shivaxi** [comment]
I am hoping this gets an update ASAP as I am preparing to release RLCraft v2.8 and I would love to have this fixed by then, otherwise I may need to look for an alternate disenchanting mod.  Is there an ETA on a fix for this?

**Comment by Impelon** [comment]
I will eventually get to update the mod, but I am very occupied with university right now.
What is an ETA you are looking for? I would like to push an update with fixes for everything and that would take a few days to develop, if I have the time for it, which at least until the weekend I cannot begin with that certainly; probably not even during the weekend... I'm not even sure there are any other standalone disenchanting mods, although you are free to check yourself of course. 

By now I do feel enough pressure coming from new users (aka. from RLCraft) to fix these issues, but I really do not have the time to do this right now. It might take more than until the end of the month to find enough free time. If that's fine with you I might try harder to find the time to do this...

**Comment by Shivaxi** [comment]
I was hoping to to push out an update come the weekend.  If you'd like, I know some devs that would be willing to help, if this is open source, they can submit some changes to the github and then all you'd have to do is push them.

**Comment by Impelon** [comment]
Well I'm using the BSD-license and as you can [see yourself](https://github.com/Impelon/Disenchanter/blob/1.12/LICENSE) it is very short and to the point. Yes this is open-source, if it was closed, the sourcecode would not be on GitHub publicly. You could even fix this issue yourself and redistribute a fixed version yourself; that would be legal with my license, and I would not care, that would be fine.

That being said, I do welcome good quality additions and contributions. I will say that I don't belive there are that many developers willing to work with my undocumented code, but you might as well prove me wrong.

I'll try to fit you into my schedule, but it's tight.

**Comment by Impelon** [comment]
I've added everything I'm thinking of fixing into a todo-list. Also if this gives you some reasurement, I've just setup my ForgeGradle workspace for 1.12.2 again...

**Comment by Impelon** [comment]
@maxerium Thanks for the report, I've been able to reproduce this.

**Comment by Impelon** [comment]
I see @maksymsen published a hotfix in #49. I've pulled it into my update-branch.

Tomorrow I will test the new code and publish a new version on curse with this hotfix so you can have your update.

**Comment by Impelon** [comment]
You can find the new version [here](https://www.curseforge.com/minecraft/mc-mods/the-disenchanter-mod/files/2815489). I'll keep this issue open, until I roll out a major release.
