### ISSUE TITLE
Enchantment Dupe using automatic Disenchantment Table

### ISSUE THREAD

**Issue by efornum** [Impelon/Disenchanter#50]
## Summary
When an enchanted item is extracted automatically the disenchantment process is not aborted.
Interestingly, this also bricks the table and it needs to be broken and replaced before being usable again.
## Steps to Reproduce
- place an automatic disenchantment table on a hopper.
- place a book in the book slot.
- place any enchanted item in the first slot.

The enchanted item will be extracted and shortly thereafter the enchantment is applied to the empty book.

**Comment by Impelon** [comment]
Thanks for the detailed issue! The automatic version needs to be reworked regardles. At the moment it is barely funcțional.

**Comment by Impelon** [comment]
Nevermind, this is very much still an issue!

Reproduceable when the item is destroyed in the disenchantment-process.

**Comment by Impelon** [comment]
Nevermind, again. Turns out my testing-setup was just bad and there was no duplication happening. Closed again.
