### ISSUE TITLE
Bypassing enchanting limit

### ISSUE THREAD

**Issue by LLjo** [Impelon/Disenchanter#53]
So you can easily bypass the enchanting limit by enchanting an item. then disenchant 1 or 2 times, put those 2 enchant books together and enchant again, then disenchant 1 time and put it together with some other enchant.  This way you can put as many enchants as you want.

 1.12.2 forge-14.23.5.2854
Most recent disenchanter file

**Comment by Impelon** [comment]
Hey,
I suppose you are talking about the vanilla "enchanting limit", aka. the fact that an enchaning table can only get you so far with enchantments. Also probably to the fact, that when you combine enchantments in an anvil, it costs increasingly more experience to get better gear, up to a limit when it it impossible?

If I get you right, than there is not much I can think of, to prevent that from happening.
What do you propose?

**Comment by Impelon** [comment]
I'm closing this, as I received no feedback, and I feel that this would be resolved by #37
