### ISSUE TITLE
Custom name (given via anvil) is not persistently displayed

### ISSUE THREAD

**Issue by Impelon** [Impelon/Disenchanter#55]
As with vanilla containers, the disenchantment table can be renamed in an anvil to give it a custom name.
This custom name will be displayed when first placed down and opened, but after reloading the game, the custom name will disappear.

This is not intended, instead the name should be persistent.

**Comment by Impelon** [comment]
In fact the nbt-data is saved correctly, also the tile entity knows it has a custom name server-side.
The problem is, that on the client, the tile entity says it does not have a custom name.

**Comment by Impelon** [comment]
Custom name needs to be synchronized with the client, see here:
- https://forums.minecraftforge.net/topic/76025-1144solved-tileentity-not-working-properly/
- https://forums.minecraftforge.net/topic/64749-solved-1122-my-tile-entity-returns-custom-name-only-spectator/
- https://mcforge.readthedocs.io/en/1.12.x/tileentities/tileentity/#synchronizing-on-block-update

**Comment by DoomRater** [comment]
Kudos for running the tracker like someone else might actually see it!

**Comment by Impelon** [comment]
Thanks! I've recently started doing that. It's also useful for me, because i can easily keep track of what still needs to be done and what the issue is exactly. This is especially useful if i don't resolve the issue when i find it...
