### ISSUE TITLE
destroy items that don't have durability

### ISSUE THREAD

**Issue by Shivaxi** [Impelon/Disenchanter#59]
One of the things I'd love is an option to allow the destruction of items that don't usually have a durability bar, such as enchanted books. I use this so that users can only rip off enchants 1 at a time from tools and such, and in the process, destroy the item. However since enchanted books of course don't have or use durability, they can pull off every single enchantment from said enchanted book.

**Comment by Impelon** [comment]
Hey, thanks for the suggestion!

So you'd like to have the option to destroy any item that is being disenchanted after its first use?
Would this also include items that already have durability? Some sort of one-time disenchantment?

Or rather the disenchanting of items with durability will work as before, but for items without durability it will delete them after one use? 
Should it really be only one time only? The durability cannot be used as reference, but with custom NBT-tags I could count the number of disenchantments made for every item (and count this for items with durability, too).

I would like to get a better understanding of what your idea is exactly.

**Comment by Shivaxi** [comment]
yeah this could be a separate option that just gives you the option to destroy items if it has no durability, otherwise fall back on the durability damage you do.  Cuz currently for RLCraft I have durablity damage set to do like 999999 damage haha, in order to instant destroy anything

**Comment by Impelon** [comment]
Got it! 
I might as well put it on the to-do list for a future update, it is easy enough to implement.
Will not be any time soon though. 

If you are keen on this feature, I can point you to the changes needed to implement this (if you are able to code and compile yourself, you could make a pull-request with the changes), or I could provide you with a updated mod-jar that includes the change (without the option to turn the item-deletion off).
To implement a rough version of this you basically have to insert 2 lines of code.

**Comment by Shivaxi** [comment]
pull request done :)

https://github.com/Impelon/Disenchanter/pull/60

**Comment by Impelon** [comment]
Looks good!
If you can compile the changes yourself, then you are set. If not I can compile them for you.

I will not release this as a new version yet, since I feel like more changes should happen between version bumps.

**Comment by Impelon** [comment]
#60 is merged into the update-branch now, this issue will remain open until the changes are merged into the 1.12 branch when a new update is released.

**Comment by Impelon** [comment]
A new update has been released, I just forgot to close this issue as resolved.
Doing that now!
