### ISSUE TITLE
Feature Request - Add config option for auto delete

### ISSUE THREAD

**Issue by skruis** [Impelon/Disenchanter#7]
My mob grinders have generated thousands of pieces of enchanted armor and I'm trying to process them in the auto disenchanter (thanks for creating this btw) but after an item has been stripped of all it's enchantments, it will remain in the auto disenchanter if it wasn't destroyed as part of the durability penalty. Currently, I have to pipe the non-enchanted, non-book items out of the table or manually remove them to clear the jam when I'd rather the table simply purged (deleted) an item if it has been stripped of enchantments by the table and is no longer enchanted. I figure this could be a config option that the users could enable and if it's an item that the enchantment table has 'created' by way of disenchanting an enchanted item (I'm guessing that's how it works in the background), you would know that it's 'your' item and not an item that was piped in. That would allow you to delete no longer enchanted items while avoiding deleting items that got piped in by accident.

Thanks,

bus

**Comment by Impelon** [comment]
Yeah, seems like a good addition; I will add it if I find some time to work on this over the holidays;

_(Also I would just check, if there are any enchantments left after the disenchantment; just in case you're wondering how it would work =p)_

**Comment by Impelon** [comment]
Sooo... fixed? Only took bout 4 months
